### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by jonyvx** [acidvegas/trollbots#2]
hello and thank you very very much for creating efknocker and badparent and surge....but please explain how to make them work properly ?

badparent and surge want ....<input> file to scan....?what this mean ? what file ? for proxy or servers ?
efknocker works good but it stops after some servers and give error loop (9) bad discriptor (timed out)
and it dosnt post or type message ..it only join >> part >> leave message for part (part_msg)

please fix and update efknocker please please...and teach me how to run badparent and surge...thank you very much for your efforts and your time to make these cool awsome fun great scripts.

**Comment by Rhodesia** [comment]
can you describe your problem in more detail?

**Comment by Rhodesia** [comment]
terminal output would help, no idea about that script. Please try to stay on topic to tools in this repository only. Thanks!

**Comment by jonyvx** [comment]
i dont understand what you mean terminal output ,,,could download and run the script of surge.py and badparent ? and see if you can make it work and tell me how to make it work ? that would solve the problem fast

**Comment by Rhodesia** [comment]
?
go into your terminal and type `python3.6 blah` and give me the output

**Comment by jonyvx** [comment]
if i type python3.6 blah ... i get error message : python3.6: can't open file 'blah': [Errno 2] No such file or directory

and if i type python3.6 badparent.py ....i get..

usage: badparent.py <input> [options] 
badparent.py: error: the following arguments are required: input


i get same errors if i run surge.py.
thanks

**Comment by Rhodesia** [comment]
https://github.com/acidvegas/trollbots/blob/master/badparent/badparent/badparent.py#L319
input = your config

**Comment by jonyvx** [comment]
you mean the config.py file ? i must type its path with badparent.py in terminal ?

**Comment by Rhodesia** [comment]
yes

**Comment by jonyvx** [comment]
thanks man i will try now...but i thought the script will automatically read from config.py from same folder..

what about efknockr ? it stops completly before completing all servers and it dosnt post (PRIVMSG) to all channels/rooms...its just join...then leave

thanks again

**Comment by Rhodesia** [comment]
what irc network are you testing this on? Some have a a minimum time connect before LIST can be executed

**Comment by jonyvx** [comment]
i tried typing in terminal : 
python3 badparent.py  config.py      

hit enter
i get error
[!] - Invalid arguments.

please can you run it in your pc and give me picture of it of what <input> file to scan is ?

**Comment by jonyvx** [comment]
am testing it on fast working irc network on mirc

**Comment by jonyvx** [comment]
can you make video on youtube and delete it after 2 hours just so i see what file to put ? i put config.py but still gets error message.

**Comment by iczero** [comment]
Sounds awfully like one of those script kiddies who don't know how to code
If you don't know how to code, go away.
