### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by jonyvx** [acidvegas/trollbots#3]
can you please explain little bit on how to use surge.py ? what is "file to scan" input ?
thanks

**Comment by acidvegas** [comment]
`parser.add_argument('-p', '--proxy', help='proxy list', action='store_true')`
`parser.add_argument('-v', '--vhost', help='vhost list', action='store_true')`

It is pretty easy to see....you are flooding from either socks, or vhosts, so you compile them into a text file and pass it as an argument to the script, specifying if it is a socks list or a vhost list.

**Comment by jonyvx** [comment]
but when i use -p proxyList.txt it say install pyp modules ,,,and when i use -v vhostlist.txt its instantly says ..flooding completed...without even flooding anything.....i dont understand how this works !!!

in readme file ..it says proxy socks is optional ...can't i use surge.py and badparent.py without proxy and without vhost ? like efknockr ?

can you please make a simple bot to send private messages to all users in all irc/servers/channels/networks ? on mirc or python or perl...you really make good scripts but some of them have weird strange way to work ...which is it not easy to understand.

i still unable to make surge.py work or badparent.py if you be kind and make youtube video on how to make it work ? please ..thank you very much.

**Comment by jonyvx** [comment]
another thing is how to install pyp python3 socks modules ? like pip3 install socks ? or python3 install socks ? please write command line to install python socks modules i searched in that website and didnt understand how to install python socks modules...again thank you very much in advance.

**Comment by acidvegas** [comment]
I think this script is a little bit beyond your level....
Maybe you should learn a little about Python and IRC instead of trying to be a skid right away.
