### ISSUE TITLE
"some assembly required" to reduce spamming?

### ISSUE THREAD

**Issue by 6a68** [acidvegas/trollbots#4]
Hey - would you consider breaking these libraries into component chunks, to make it a little harder for semi-literate script kiddies to spam freenode?

<img width="587" alt="screen shot 2018-01-17 at 5 19 10 pm" src="https://user-images.githubusercontent.com/96396/35075955-caede900-fbaa-11e7-97a4-325d1262762a.png">

The spamming IP belongs to some provider in Illinois, USA, so I assume this wasn't you ;-)

I'm thinking "some assembly required" might make this code just as useful to legit developers, but prevent use by people not smart enough to assemble the pieces. ¯\_(ツ)_/¯

**Comment by moonheart08** [comment]
This. Freenode is having a few spam incidents due to this annoying bot. ):

**Comment by acidvegas** [comment]
component chunks?

**Comment by Rhodesia** [comment]
```
I am not responsible for any malicious actions or damages caused by these scripts.

These bots are used for testing against your own server(s) in an effort to better understand flood mitigation.
```
I thought freenode was the place where people yell at people to read the fucking manual, I guess not

**Comment by jonyvx** [comment]
i dont know how to use the surge.py script....and i dont know how to use badparents.py script....i dont know what to file to put for them to work. 

    On Thursday, January 18, 2018 4:31 AM, Jared Hirsch <notifications@github.com> wrote:
 

 Hey - would you consider breaking these libraries into component chunks, to make it a little harder for semi-literate script kiddies to spam freenode?The spamming IP belongs to some provider in Illinois, USA, so I assume this wasn't you ;-)I'm thinking "some assembly required" might make this code just as useful to legit developers, but prevent use by people not smart enough to assemble the pieces. ¯_(ツ)_/¯—

**Comment by acidvegas** [comment]
None of these are issues with the code itself more so as it is a lacking of your understanding of Python and how to use an open source program. Stop bugging me.

**Comment by jonyvx** [comment]
i know ...but i thought you could give me instructions on how to use it....for example what file to put in the <input> file ? ...thanks anyway 

    On Sunday, January 21, 2018 8:53 AM, Dionysus <notifications@github.com> wrote:
 

 None of these are issues with the code itself more so as it is a lacking of your understanding of Python and how to use an open source program. Stop bugging me.—

**Comment by 6a68** [comment]
> component chunks?

@acidvegas Yup, instead of publishing scripts that can be used to directly troll freenode, just publish libraries that can be wired together into scripts. The stated purpose of the repo is to help people stress-test their own IRC networks, and I'd think any admin could handle putting the libraries together.

It's wonderfully ironic that this bug (about making changes to reduce abuse by trollish newbs) was closed due to annoying questions from a trollish newb

**Comment by acidvegas** [comment]
This isnt an "issue" this is a suggestion. The code is open source, you are free to fork it.

While I am not responsible for how people chose to use my scripts, I am quite aware that it will be used by trolls to troll other peoples networks. I find it hilarious that Freenode is getting abused by my scripts. Hopefully they learn a thing or two about how easy IRCd's can be abused.
